'''
Module: PersonName
It writes the given figure (upto 999 trillion) in words.

Version: 1.0

Author:
   Farhat Pachisa (farhat.pachisa@homecampus.com.sg)
   
Copyright:
    Copyright (c) 2010, Home Campus.  All Rights Reserved.

Usage:
  

History:
  
'''
PersonName = ("Adrian","John",
              "Wynn Chang","Hady","Bala","Jeremy","Lee",
              "Lim","Stephanie","Mary",
              "Nora",
              "Maya","Geetha","Lynn",
              "Annie","Mia","Olivia","Neil","Fiona","Mala","Mei","Jill","Ben","Li",
              "Charlie","Dave","Eli","Aaron","Abel","Abraham","Adriel","Adrien","Agustin","Ahmed","Alan","Albert","Alberto","Alec","Alex","Alexander","Alfonso","Alfred","Ali","Alonso","Alvin","Amir","Anderson","Andre","Andrew","Andy","Angelo","Anthony","Antonio","Anthony","Ariel","Arjun","Arnold","Aron","Arthur","Aryan","Asher","Ashton","Austin","Barry","Ben","Benjamin","Bernard","Bilal","Billy","Bobby","Brad","Bradley","Brandon","Brendan","Bret","Brett","Brian","Brock","Bruce","Bruno","Bryan","Caleb","Calvin","Carl","Carlo","Carlos","Carlton","Cesar","Chandler","Charles","Charlie","Chris","Christopher","Clark","Clifford","Collin","Colt","Cooper","Corey","Craig","Curtis","Cyrus","Damien","Daniel","Danny","Darius","Darrell","Darryl","Darwin","David","Davis","Dean","Dennis","Denzel","Derek","Desmond","Destin","Devin","Devon","Diego","Dillon","Dominique","Donald","Donovan","Douglas","Dylon","Earl","Eddie","Eddy","Edgar","Edward","Edwin","Eli","Elias","Elliot","Elliott","Elvin","Elvis","Emanuel","Emilio","Emmanuel","Enrique","Eric","Erick","Erik","Ethan","Eugene","Evan","Felipe","Felix","Fernando","Fidel","Forrest","Francis","Francisco","Frank","Frankie","Franklin","Fred","Freddie","Freddy","Frederick","Fredrick","Gabriel","Garrett","Gary","Geoffrey","George","Gerald","Gerard","Gerardo","Gilbert","Gilberto","Gino","Gordon","Graham","Grant","Grayson","Gregory","Guy","Hamza","Harold","Harrison","Harry","Hassan","Hector","Henry","Herbert","Holden","Howard","Hugh","Hugo","Ian","Ibrahim","Isaac","Isaak","Ismael","Issac","Ivan","Jack","Jackson","Jacob","Jaden","Jaheem","Jake","Jakob","Jamal","James","Jamie","Jamil","Jan","Jared","Jarrod","Jason","Javier","Jay","Jean","Jeff","Jefferson","Jeffrey","Jeremy","Jermaine","Jerome","Jerry","Jesse","Jessie","Jimmy","Joan","Joaquin","Joe","Joel","Joey","John","Johnathan","Johnny","Jon","Jonathan","Jorge","Jose","Josef","Joseph","Josh","Joshua","Juan","Jude","Julio","Julius","Justin","Kai","Kale","Kaleb","Kane","Kareem","Karl","Keanu","Keenan","Keith","Kelvin","Kendrick","Kenneth","Kenny","Kent","Kevin","Khalid","Khalil","Kian","Kieran","Kobe","Kyle","Lance","Larry","Lawrence","Lee","Leo","Leon","Leonard","Leonardo","Leonel","Lewis","Lorenzo","Louis","Lucas","Lukas","Luke","Malcolm","Malik","Marc","Marcel","Marcelo","Marco","Marcos","Marcus","Mariano","Mario","Mark","Markus","Marshall","Martin","Marvin","Matthew","Maurice","Maverick","Max","Melvin","Michael","Miguel","Mike","Mitchell","Mohamed","Mohammad","Mohammed","Morgan","Muhammad","Mustafa","Nasir","Nathan","Nathaniel","Neal","Neil","Nelson","Nicholas","Nick","Nigel","Nikhil","Nikolas","Noah","Noel","Nolan","Oliver","Omar","Orlando","Oscar","Pablo","Parker","Patrick","Paul","Peter","Phillip","Pranav","Quincy","Rafael","Rahul","Ralph","Randy","Rashad","Ray","Rayan","Raymond","Ricardo","Richard","Ricky","Robert","Roberto","Rodney","Rodolfo","Rodrigo","Roger","Rohan","Romeo","Ronald","Ronaldo","Ronnie","Ross","Rowan","Roy","Russell","Ryan","Sam","Samir","Sammy","Samson","Samuel","Scott","Sean","Sebastian","Sergio","Shane","Shawn","Simon","Solomon","Stephen","Steve","Steven","Stuart","Syed","Tariq","Taylor","Terrence","Terry","Thomas","Timothy","Tobias","Toby","Todd","Tommy","Tony","Travis","Trey","Ty","Tyler","Tyson","Vernon","Victor","Vincent","Walter","Will","William","Wilson","Xavier","Yosef","Zach","Zachary","Zack","Zain","Zavier","Zion","Aadil","Aakash","Aamir","Abbas","Abhay","Abhinav","Abhijeet","Abhishek","Adarsh","Aditya","Adnan","Ahmad","Ajay","Ajit","Akhil","Akram","Akshay","Ali","Alok","Amar","Amir","Amit","Amol","Amrit","Anand","Anil","Anirudh","Aryan",
              "Aaliyah","Adeline","Adriana","Adrienne","Aisha","Alana","Alanis","Alena","Alice","Alicia","Alina","Alisha","Aliyah","Amanda","Amara","Amber","Amelia","Amina","Amira","Amy","Anastasia","Anaya","Andrea","Angel","Angelina","Anika","Anita","Anjali","Anna","Annabel","Annie","Anya","Aryanna","Ashley","Aubrey","Audrey","Barbara","Bella","Bethany","Bianca","Brenda","Bridget","Britney","Brooke","Cameron","Camila","Cara","Carina","Carla","Carol","Carolina","Carolyn","Carrie","Cassandra","Catherine","Cecilia","Celeste","Celina","Chaya","Chelsea","Chloe","Christina","Christine","Christy","Cindy","Clara","Claudia","Cynthia","Daisy","Dalia","Daphne","Darby","Darlene","Deborah","Denise","Diana","Diane","Donna","Dorothy","Eileen","Elena","Elizabeth","Ellen","Ellie","Emily","Emma","Erica","Esther","Eva","Evelyn","Faith","Falaq","Fatima","Felicia","Fiona","Frida","Gia","Gina","Gloria","Grace","Gracie","Hailey","Halle","Hannah","Hazel","Heather","Heidi","Helen","Helena","Holly","Indira","Irene","Isabelle","Ivy","Jada","Jana","Jane","Janet","Janice","Jasmine","Jennifer","Jenny","Jessica","Jessie","Joanna","Joyce","Julia","Julie","Karen","Kate","Katie","Kelly","Lana","Lara","Laura","Lila","Lilian","Lily","Lisa","Lucy","Maggie","Margaret","Maria","Mariam","Mariana","Marilyn","Mary","Maryam","Maya","Megan","Melissa","Melody","Mia","Michelle","Mina","Miriam","Molly","Monica","Nadia","Nancy","Natasha","Nathalie","Nicole","Nikki","Nina","Nora","Olivia","Paige","Pamela","Patricia","Paula","Phoebe","Piper","Rachel","Rebecca","Regina","Rita","Robin","Rose","Roxana","Ruby","Ruth","Sabrina","Sally","Salma","Samantha","Samara","Samira","Sandra","Sandy","Sara","Sarah","Sasha","Serena","Shakira","Sharon","Sheila","Shreya","Sofia","Sonia","Sonya","Sophie","Stacey","Stacy","Stella","Stephanie","Susan","Sylvia","Tanya","Tara","Teresa","Tess","Tia","Tina","Vanessa","Veronica","Victoria","Vivian","Wendy","Yasmin","Yasmine","Zoe","Zoey",)

BoyName = ("Adrian","John",
              "Wynn Chang","Hady","Bala","Jeremy","Lee",
              "Lim","Neil","Jack","Tim","Ben","Charlie","Dave","Aaron","Abel","Abraham","Adriel","Adrien","Agustin","Ahmed","Alan","Albert","Alberto","Alec","Alex","Alexander","Alfonso","Alfred","Ali","Alonso","Alvin","Amir","Anderson","Andre","Andrew","Andy","Angelo","Anthony","Antonio","Anthony","Ariel","Arjun","Arnold","Aron","Arthur","Aryan","Asher","Ashton","Austin","Barry","Ben","Benjamin","Bernard","Bilal","Billy","Bobby","Brad","Bradley","Brandon","Brendan","Bret","Brett","Brian","Brock","Bruce","Bruno","Bryan","Caleb","Calvin","Carl","Carlo","Carlos","Carlton","Cesar","Chandler","Charles","Charlie","Chris","Christopher","Clark","Clifford","Collin","Colt","Cooper","Corey","Craig","Curtis","Cyrus","Damien","Daniel","Danny","Darius","Darrell","Darryl","Darwin","David","Davis","Dean","Dennis","Denzel","Derek","Desmond","Destin","Devin","Devon","Diego","Dillon","Dominique","Donald","Donovan","Douglas","Dylon","Earl","Eddie","Eddy","Edgar","Edward","Edwin","Eli","Elias","Elliot","Elliott","Elvin","Elvis","Emanuel","Emilio","Emmanuel","Enrique","Eric","Erick","Erik","Ethan","Eugene","Evan","Felipe","Felix","Fernando","Fidel","Forrest","Francis","Francisco","Frank","Frankie","Franklin","Fred","Freddie","Freddy","Frederick","Fredrick","Gabriel","Garrett","Gary","Geoffrey","George","Gerald","Gerard","Gerardo","Gilbert","Gilberto","Gino","Gordon","Graham","Grant","Grayson","Gregory","Guy","Hamza","Harold","Harrison","Harry","Hassan","Hector","Henry","Herbert","Holden","Howard","Hugh","Hugo","Ian","Ibrahim","Isaac","Isaak","Ismael","Issac","Ivan","Jack","Jackson","Jacob","Jaden","Jaheem","Jake","Jakob","Jamal","James","Jamie","Jamil","Jan","Jared","Jarrod","Jason","Javier","Jay","Jean","Jeff","Jefferson","Jeffrey","Jeremy","Jermaine","Jerome","Jerry","Jesse","Jessie","Jimmy","Joan","Joaquin","Joe","Joel","Joey","John","Johnathan","Johnny","Jon","Jonathan","Jorge","Jose","Josef","Joseph","Josh","Joshua","Juan","Jude","Julio","Julius","Justin","Kai","Kale","Kaleb","Kane","Kareem","Karl","Keanu","Keenan","Keith","Kelvin","Kendrick","Kenneth","Kenny","Kent","Kevin","Khalid","Khalil","Kian","Kieran","Kobe","Kyle","Lance","Larry","Lawrence","Lee","Leo","Leon","Leonard","Leonardo","Leonel","Lewis","Lorenzo","Louis","Lucas","Lukas","Luke","Malcolm","Malik","Marc","Marcel","Marcelo","Marco","Marcos","Marcus","Mariano","Mario","Mark","Markus","Marshall","Martin","Marvin","Matthew","Maurice","Maverick","Max","Melvin","Michael","Miguel","Mike","Mitchell","Mohamed","Mohammad","Mohammed","Morgan","Muhammad","Mustafa","Nasir","Nathan","Nathaniel","Neal","Neil","Nelson","Nicholas","Nick","Nigel","Nikhil","Nikolas","Noah","Noel","Nolan","Oliver","Omar","Orlando","Oscar","Pablo","Parker","Patrick","Paul","Peter","Phillip","Pranav","Quincy","Rafael","Rahul","Ralph","Randy","Rashad","Ray","Rayan","Raymond","Ricardo","Richard","Ricky","Robert","Roberto","Rodney","Rodolfo","Rodrigo","Roger","Rohan","Romeo","Ronald","Ronaldo","Ronnie","Ross","Rowan","Roy","Russell","Ryan","Sam","Samir","Sammy","Samson","Samuel","Scott","Sean","Sebastian","Sergio","Shane","Shawn","Simon","Solomon","Stephen","Steve","Steven","Stuart","Syed","Tariq","Taylor","Terrence","Terry","Thomas","Timothy","Tobias","Toby","Todd","Tommy","Tony","Travis","Trey","Ty","Tyler","Tyson","Vernon","Victor","Vincent","Walter","Will","William","Wilson","Xavier","Yosef","Zach","Zachary","Zack","Zain","Zavier","Zion","Aadil","Aakash","Aamir","Abbas","Abhay","Abhinav","Abhijeet","Abhishek","Adarsh","Aditya","Adnan","Ahmad","Ajay","Ajit","Akhil","Akram","Akshay","Ali","Alok","Amar","Amir","Amit","Amol","Amrit","Anand","Anil","Anirudh","Aryan")

GirlName = ("Stephanie","Mary",
              "Nora",
              "Maya","Geetha","Lynn",
              "Annie","Mia","Olivia","Fiona","Mala","Mei","Jill","Li","Eli","Aaliyah","Adeline","Adriana","Adrienne","Aisha","Alana","Alanis","Alena","Alice","Alicia","Alina","Alisha","Aliyah","Amanda","Amara","Amber","Amelia","Amina","Amira","Amy","Anastasia","Anaya","Andrea","Angel","Angela","Angelina","Angie","Anika","Anita","Anjali","Ann","Anna","Annabel","Annie","Anya","Aryanna","Ashlee","Ashley","Aubrey","Audrey","Barbara","Bella","Bethany","Bianca","Brenda","Bridget","Britney","Brooke","Cameron","Camila","Cara","Carina","Carla","Carol","Carolina","Caroline","Carolyn","Carrie","Cassandra","Catherine","Cecilia","Celeste","Celina","Chaya","Chelsea","Chloe","Christina","Christine","Christy","Cindy","Clara","Claudia","Cynthia","Daisy","Dalia","Daphne","Darby","Darlene","Deborah","Denise","Diana","Diane","Donna","Dorothy","Eileen","Elena","Elizabeth","Elle","Ellen","Ellie","Emily","Emma","Erica","Erika","Esther","Eva","Evelyn","Faith","Falaq","Fatima","Felicia","Fiona","Frida","Gia","Gina","Gloria","Grace","Gracie","Hailey","Halle","Hannah","Hazel","Heather","Heidi","Helen","Helena","Holly","Indira","Irene","Isabelle","Ivy","Jada","Jana","Jane","Janet","Janice","Jasmine","Jennifer","Jenny","Jessica","Jessie","Joanna","Joyce","Julia","Julie","Karen","Kate","Katie","Kelly","Lana","Lara","Laura","Lila","Lilian","Lily","Lisa","Lucy","Maggie","Margaret","Maria","Mariam","Mariana","Marilyn","Mary","Maryam","Maya","Megan","Melissa","Melody","Mia","Michelle","Mina","Miriam","Molly","Monica","Nadia","Nancy","Natasha","Nathalie","Nicole","Nikki","Nina","Nora","Olivia","Paige","Pamela","Patricia","Paula","Phoebe","Piper","Rachel","Rebecca","Regina","Rita","Rose","Roxana","Ruby","Ruth","Sabrina","Sally","Salma","Samantha","Samara","Samira","Sandra","Sandy","Sara","Sarah","Sasha","Serena","Shakira","Sharon","Sheila","Shreya","Sofia","Sonia","Sonya","Sophie","Stacey","Stacy","Stella","Stephanie","Susan","Sylvia","Tanya","Tara","Teresa","Tess","Tia","Tina","Vanessa","Veronica","Victoria","Vivian","Wendy","Yasmin","Yasmine","Zoe","Zoey")

AuntyName = ('Mrs. Smith',
'Mrs. Johnson',
'Mrs. Williams',
'Mrs. Jones',
'Mrs. Brown',
'Mrs. Davis',
'Mrs. Miller',
'Mrs. Wilson',
'Mrs. Moore',
'Mrs. Taylor',
'Mrs. Thomas',
'Mrs. Jackson',
'Mrs. Garcia',
'Mrs. Martinez',
'Mrs. Rodriguez',
'Mrs. Lewis',
'Mrs. Lee',
'Mrs. Tan',
'Mrs. Young',
'Mrs. Lopez',
'Mrs. Scott',
'Mrs. Adams',
'Mrs. Baker',
'Mrs. Gonzalez',
'Mrs. Carter',
'Mrs. Perez',
'Mrs. Roberts',
'Mrs. Turner',
'Mrs. Phillips',
'Mrs. Campbell',
'Mrs. Parker',
'Mrs. Sanchez',
'Mrs. Morris',
'Mrs. Rogers',
'Mrs. Bell',
'Mrs. Murphy',
'Mrs. Cooper',
'Mrs. Peterson',
'Mrs. Gray',
'Mrs. Ramirez',
'Mrs. Brooks',
'Mrs. Ross',
'Mrs. Powell',
'Mrs. Hughes',
'Mrs. Simmons',
'Mrs. Russell',
'Mrs. Ford',
'Mrs. Hamilton',
'Mrs. Woods',
'Mrs. Jordan',
'Mrs. Mills',
'Mrs. Wang',
'Mrs. Cheung',
'Mrs. Chang',
'Mrs. Lau',
'Mrs. Lam',
'Mrs. Li',
'Mrs. Chan',
'Mrs. Foo',
'Mrs. Yeung',
'Mrs. Chow',
'Mrs. Kwok',
'Mrs. Cheng',
'Mrs. Tong',
'Mrs. Ali',
'Mrs. Kumar',
'Mrs. Gupta',
'Mrs. Singh',
'Mrs. Raman',
'Mrs. Pillai',
'Mrs. Choi',
'Mrs. Yip',
'Mrs. Yam',
'Mrs. Sharma',
'Mrs. Verma',
'Mrs. Gupta',
'Mrs. Malhotra',
'Mrs. Bhatnagar',
'Mrs. Saxena',
'Mrs. Kapoor',
'Mrs. Kapur',
'Mrs. Singh',
'Mrs. Mehra',
'Mrs. Chopra',
'Mrs. Sarin',
'Mrs. Malik',
'Mrs. Sen',
'Mrs. Bose',
'Mrs. Das',
'Mrs. Dutta',
'Mrs. Rao',
'Mrs. Khan',
'Mrs. Yadav',
'Mrs. Shah',
'Mrs. Mehta',
'Mrs. Patel',
'Mrs. Patil',
'Mrs. Rehman',
'Mrs. Mohamed',
'Mrs. Rangan',
)

UncleName = ('Mr. Smith',
'Mr. Johnson',
'Mr. Williams',
'Mr. Jones',
'Mr. Brown',
'Mr. Davis',
'Mr. Miller',
'Mr. Wilson',
'Mr. Moore',
'Mr. Taylor',
'Mr. Thomas',
'Mr. Jackson',
'Mr. Garcia',
'Mr. Martinez',
'Mr. Rodriguez',
'Mr. Lewis',
'Mr. Lee',
'Mr. Tan',
'Mr. Young',
'Mr. Lopez',
'Mr. Scott',
'Mr. Adams',
'Mr. Baker',
'Mr. Gonzalez',
'Mr. Carter',
'Mr. Perez',
'Mr. Roberts',
'Mr. Turner',
'Mr. Phillips',
'Mr. Campbell',
'Mr. Parker',
'Mr. Sanchez',
'Mr. Morris',
'Mr. Rogers',
'Mr. Bell',
'Mr. Murphy',
'Mr. Cooper',
'Mr. Peterson',
'Mr. Gray',
'Mr. Ramirez',
'Mr. Brooks',
'Mr. Ross',
'Mr. Powell',
'Mr. Hughes',
'Mr. Simmons',
'Mr. Russell',
'Mr. Ford',
'Mr. Hamilton',
'Mr. Woods',
'Mr. Jordan',
'Mr. Mills',
'Mr. Wang',
'Mr. Cheung',
'Mr. Chang',
'Mr. Lau',
'Mr. Lam',
'Mr. Li',
'Mr. Chan',
'Mr. Foo',
'Mr. Yeung',
'Mr. Chow',
'Mr. Kwok',
'Mr. Cheng',
'Mr. Tong',
'Mr. Ali',
'Mr. Kumar',
'Mr. Gupta',
'Mr. Singh',
'Mr. Raman',
'Mr. Pillai',
'Mr. Choi',
'Mr. Yip',
'Mr. Yam',
'Mr. Sharma',
'Mr. Verma',
'Mr. Gupta',
'Mr. Malhotra',
'Mr. Bhatnagar',
'Mr. Saxena',
'Mr. Kapoor',
'Mr. Kapur',
'Mr. Singh',
'Mr. Mehra',
'Mr. Chopra',
'Mr. Sarin',
'Mr. Malik',
'Mr. Sen',
'Mr. Bose',
'Mr. Das',
'Mr. Dutta',
'Mr. Rao',
'Mr. Khan',
'Mr. Yadav',
'Mr. Shah',
'Mr. Mehta',
'Mr. Patel',
'Mr. Patil',
'Mr. Rehman',
'Mr. Mohamed',
'Mr. Rangan',
)

ShortUncleName = ('Mr Lee',
'Mr Tan',
'Mr Adam',
'Mr Bell',
'Mr Gray',
'Mr Ross',
'Mr Ford',
'Mr Wang',
'Mr Lau',
'Mr Lam',
'Mr Li',
'Mr Chan',
'Mr Foo',
'Mr Chow',
'Mr Kwok',
'Mr Tong',
'Mr Ali',
'Mr Rama',
'Mr Choi',
'Mr Yip',
'Mr Yam',
'Mr Sen',
'Mr Bose',
'Mr Das',
'Mr Rao',
'Mr Khan',
'Mr Shah',
)